In [1]:
from helper import * 
import numpy as np 


path = 'data'
data = load_data(f"{path}/driving_log.csv")

# balance_data(data, 'Steering')

img_arr, steering_arr = load_data_to_array(path, data)
img_arr, steering_arr

(array(['data\\IMG\\center_2022_10_18_15_59_57_016.jpg',
        'data\\IMG\\center_2022_10_18_15_59_57_085.jpg',
        'data\\IMG\\center_2022_10_18_15_59_57_233.jpg', ...,
        'data\\IMG\\center_2022_10_19_08_16_07_822.jpg',
        'data\\IMG\\center_2022_10_19_08_16_07_905.jpg',
        'data\\IMG\\center_2022_10_19_08_16_07_990.jpg'], dtype='<U43'),
 array([0., 0., 0., ..., 0., 0., 0.]))

In [3]:
import matplotlib.pyplot as plt 

img, steering = img_preprocess_pipeline(img_arr, steering_arr)
print(img[0])

[[[0.16470588 0.50588235 0.48627451]
  [0.14901961 0.50588235 0.48627451]
  [0.1372549  0.50588235 0.48627451]
  ...
  [0.43529412 0.45882353 0.50196078]
  [0.43529412 0.4627451  0.50196078]
  [0.41176471 0.46666667 0.50196078]]

 [[0.16470588 0.50588235 0.48627451]
  [0.14901961 0.50588235 0.48627451]
  [0.1372549  0.50588235 0.48627451]
  ...
  [0.42745098 0.45882353 0.50196078]
  [0.43137255 0.4627451  0.50196078]
  [0.40784314 0.4627451  0.50196078]]

 [[0.16078431 0.50588235 0.48627451]
  [0.14901961 0.50588235 0.48627451]
  [0.1372549  0.50588235 0.48627451]
  ...
  [0.40784314 0.45882353 0.50196078]
  [0.42745098 0.4627451  0.50196078]
  [0.4        0.4627451  0.50196078]]

 ...

 [[0.67843137 0.49411765 0.51372549]
  [0.6745098  0.49411765 0.51372549]
  [0.6745098  0.49411765 0.51372549]
  ...
  [0.57647059 0.49411765 0.50980392]
  [0.58039216 0.49411765 0.50980392]
  [0.58431373 0.49411765 0.50980392]]

 [[0.6745098  0.49411765 0.51372549]
  [0.67058824 0.49411765 0.51372549]
